### ISSUE TITLE
Decide whether we should use CDN or embedded javascript by default

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#26]
Which one do we want to be the default. If someone tries to view an old heap profile in 5 years then the one with embedded javascript is more likely to work but I suppose heap profiles are ephemeral so the CDN option is better.

_Originally posted by @mpickering in https://github.com/mpickering/hp2pretty/pull/22#issuecomment-503437022_

**Comment by BinderDavid** [comment]
The file sizes are currently:
- HTML 2.5 KB
- Vega Javascript libraries: 650 KB
- JSON generated from ghc.eventlog: 40 KB (This depends on the analyzed  eventlog, of course)

Having a small generated HTML file (with the embedded JSON) should be the standard, since this allows easy sharing of generated HTMLs via Email/Slack etc. 
I think, including the javascript should be the non-default option for working offline.

**Comment by BinderDavid** [comment]
We agreed to use the CDN as the default and give the user the option to include javascript.

**Comment by mpickering** [comment]
I have heard a conflicting request to bundle javascript libraries by default. The argument is essential that criterion already does this. It has the big advantage that the files will continue to work (for example - http://www.serpentine.com/criterion/fibber.html)

I think we should change the default here. People aren't usually short on disk space.

**Comment by BinderDavid** [comment]
Ok, I'll fix this.

**Comment by mpickering** [comment]
I have already done it.. so stop if you have started.

**Comment by mpickering** [comment]
The size with everything bundled in `739k`
